senna_wrapper_master:
    script:
        - mvn source:jar deploy -B
    tags:
        - mvn
    only:
        - master

senna_wrapper_branches:
    script:
        - mvn test -B
    tags:
        - mvn
    only:
        - branches
    except:
        - master
